apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-data
  namespace: kube-logging
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: do-block-storage