apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-data
  namespace: kube-logging
spec:
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce